//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VueASPDemo.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChargeCategory()
        {
            this.PayInfo = new HashSet<PayInfo>();
        }
    
        public int CCID { get; set; }
        public string CCName { get; set; }
        public string CCMark { get; set; }
        public Nullable<bool> ISDate { get; set; }
        public Nullable<bool> CCState { get; set; }
        public string CCColumn1 { get; set; }
        public string CCColumn2 { get; set; }
        public string CDateColumn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayInfo> PayInfo { get; set; }
    }
}
