//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VueASPDemo.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employs()
        {
            this.Lets = new HashSet<Lets>();
        }
    
        public int EmpID { get; set; }
        public Nullable<int> DepID { get; set; }
        public Nullable<int> DutyID { get; set; }
        public string LoginName { get; set; }
        public string LoginPWD { get; set; }
        public string EmpName { get; set; }
        public string EmpSex { get; set; }
        public string EmpTel { get; set; }
        public string EmpAdd { get; set; }
        public Nullable<int> EmpState { get; set; }
        public string EmpMark { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Dutys Dutys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lets> Lets { get; set; }
    }
}
