//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VueASPDemo.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HouseInfo()
        {
            this.Lets = new HashSet<Lets>();
        }
    
        public int HID { get; set; }
        public Nullable<int> HCID { get; set; }
        public string HAdd { get; set; }
        public string HNum { get; set; }
        public string HType { get; set; }
        public Nullable<int> HArea { get; set; }
        public string HDirection { get; set; }
        public Nullable<decimal> HRent { get; set; }
        public Nullable<decimal> HNet { get; set; }
        public Nullable<decimal> HElectric { get; set; }
        public Nullable<decimal> HWater { get; set; }
        public Nullable<decimal> HElectricMoney { get; set; }
        public Nullable<decimal> HWaterMoney { get; set; }
        public string HMark { get; set; }
        public Nullable<int> HState { get; set; }
    
        public virtual HouseCategory HouseCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lets> Lets { get; set; }
    }
}
