//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VueASPDemo.Models.EFModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LetDBEntities : DbContext
    {
        public LetDBEntities()
            : base("name=LetDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ChargeCategory> ChargeCategory { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Dutys> Dutys { get; set; }
        public virtual DbSet<Employs> Employs { get; set; }
        public virtual DbSet<HouseCategory> HouseCategory { get; set; }
        public virtual DbSet<HouseInfo> HouseInfo { get; set; }
        public virtual DbSet<JurisdicDuty> JurisdicDuty { get; set; }
        public virtual DbSet<Jurisdictions> Jurisdictions { get; set; }
        public virtual DbSet<Lets> Lets { get; set; }
        public virtual DbSet<PayInfo> PayInfo { get; set; }
        public virtual DbSet<Repair> Repair { get; set; }
    }
}
