//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VueASPDemo.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayInfo
    {
        public int PayID { get; set; }
        public Nullable<int> LetID { get; set; }
        public Nullable<int> CCID { get; set; }
        public string PayNum { get; set; }
        public Nullable<int> CreateEmp { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<decimal> PayPrice { get; set; }
        public Nullable<int> PayAmount { get; set; }
        public Nullable<System.DateTime> PayBeginDate { get; set; }
        public Nullable<System.DateTime> PayEndDate { get; set; }
        public string PayMark { get; set; }
        public Nullable<decimal> PayMoney1 { get; set; }
        public Nullable<decimal> PayMoney2 { get; set; }
        public int? PayState { get; set; }
    
        public virtual ChargeCategory ChargeCategory { get; set; }
        public virtual Lets Lets { get; set; }
    }
}
